package chromatikmcp;

import java.io.IOException;
import java.io.PrintStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Dumps every {@link chromatikmcp.tools.LxTool}'s name/description/readOnly/inputSchema as
 * JSON, sorted by name — the source of {@code site/src/data/tools.json}, regenerated by
 * {@code package/scripts/dump-tool-catalog.sh}. Lives in src/test (like {@link
 * HeadlessLoadCheck}) so it never ships in the plugin jar.
 */
public final class ToolCatalogDump {

  private ToolCatalogDump() {}

  public static void main(String[] args) {
    String json = ToolCatalogJson.catalogJson();
    if (args.length > 0) {
      try {
        Files.writeString(Path.of(args[0]), json, StandardCharsets.UTF_8);
      } catch (IOException e) {
        throw new UncheckedIOException(e);
      }
    } else {
      PrintStream out = System.out;
      out.print(json);
    }
  }
}
